version: "3.5"

services:
  app:
    build:
      context: .
      args:
        NEW_UID: ${NEW_UID:-1000}
        NEW_GID: ${NEW_GID:-1000}
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/src
      - ./secrets:/src/secrets
    ports:
      - "8510:8510"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8510/health"]
      start_period: 30s
      interval: 30m
    networks:
      zmodules:
        aliases:
          - gfmodules-nvi-referral-manager-app

  app_ssl:
    image: httpd
    restart: "no"
    ports:
      - "8550:443"
    volumes:
      - "./secrets:/usr/local/secrets"
      - "./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./docker/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf"
    networks:
      zmodules:
        aliases:
          - gfmodules-nvi-referral-manager-app

networks:
  zmodules:
    driver: bridge
    name: zmodules
