services:
  app:
    build:
      context: .
      args:
        NEW_UID: ${NEW_UID:-1000}
        NEW_GID: ${NEW_GID:-1000}
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/src
      - ./secrets:/src/secrets
    environment:
      FASTAPI_CONFIG_PATH: /src/app.conf
    ports:
      - "8515:8515"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8515/health"]
      start_period: 30s
      interval: 30m

  app_ssl:
    image: httpd
    ports:
      - "8545:443"
    volumes:
      - "./secrets:/usr/local/secrets"
      - "./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./docker/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf"
    depends_on:
      app:
        condition: service_healthy

volumes:
  secrets:
    name: secrets2