[tool.poetry]
name = "gfmodules-nvi-referral-manager-private"
version = "0.1.0"
description = ""
license = "EUPL-1.2"
authors = ["Ministerie van Volksgezondheid, Welzijn en Sport"]
repository = "https://github.com/minvws/gfmodules-nvi-referral-manager-private"
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.34"
fastapi = "^0.115.12"
mypy = "^1.16.0"
pydantic-settings = "^2.9.1"
inject = "^5.2.0"
sqlalchemy = "^2.0.41"
psycopg = { extras = ["binary", "pool"], version = "^3.2.9" }
requests = "^2.32.0"
fhir-resources = "^8.0"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.32.0"
faker = "^37.3.0"
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
pytest-mock = "^3.14.1"
httpx = "^0.28.1"
ruff = "0.11.12"
safety = "^3.3.0"
codespell = "^2.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
cache-dir = "~/.cache/ruff"
include = ["pyproject.toml", "app/*.py", "tests/*.py"]
line-length = 120

[tool.mypy]
files = "app,tests"
python_version = "3.11"
strict = true
cache_dir = "~/.cache/mypy"
ignore_missing_imports = true

[tool.pytest.ini_options]
cache_dir = "~/.cache/pytest"
testpaths = ["tests"]
