name: CI

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repositories
              uses: actions/checkout@v6

            - name: Run build action
              uses: minvws/action-python-poetry-install@v1
              with:
                python_version: "3.11"

    lint:
        name: Run code linter
        runs-on: ubuntu-24.04
        needs: build

        steps:
            - name: Checkout repositories
              uses: actions/checkout@v6

            - name: Run build action
              uses: minvws/action-python-poetry-install@v1
              with:
                python_version: "3.11"

            - name: Lint
              run: poetry run $(make lint --just-print --silent)

    type-check:
        name: Check static types
        runs-on: ubuntu-24.04
        needs: build

        steps:
            - name: Checkout repositories
              uses: actions/checkout@v6

            - name: Run build action
              uses: minvws/action-python-poetry-install@v1
              with:
                python_version: "3.11"

            - name: Check static types
              run: poetry run $(make type-check --just-print --silent)

    safety-check:
        name: Scan packages for vulnerabilities
        runs-on: ubuntu-24.04
        needs: build

        steps:
            - name: Checkout repositories
              uses: actions/checkout@v6

            - name: Run build action
              uses: minvws/action-python-poetry-install@v1
              with:
                python_version: "3.11"

            - name: Scan packages for vulnerabilities
              run: poetry run $(make safety-check --just-print --silent)

    spelling-check:
        name: Run spelling check
        runs-on: ubuntu-24.04
        needs: build

        steps:
            - name: Checkout repositories
              uses: actions/checkout@v6

            - name: Run build action
              uses: minvws/action-python-poetry-install@v1
              with:
                python_version: "3.11"

            - uses: codespell-project/codespell-problem-matcher@v1

            - name: Run spelling check
              run: poetry run $(make spelling-check --just-print --silent)

    test:
        name: Run the tests
        runs-on: ubuntu-24.04
        needs: build
        steps:
            - name: Checkout repositories
              uses: actions/checkout@v6

            - name: install liboprf
              run: |
                sudo apt update
                sudo apt install -y build-essential libsodium-dev
                git clone --depth 1 --branch v0.9.3 https://github.com/stef/liboprf.git
                cd liboprf/src
                make
                sudo make install
                sudo ldconfig

            - name: Run build action
              uses: minvws/action-python-poetry-install@v1
              with:
                python_version: "3.11"

            - name: Run the tests
              run: poetry run $(make test --just-print --silent)

            - name: Upload coverage report
              uses: actions/upload-artifact@v6
              with:
                name: coverage
                path: coverage.xml

    sonar:
        name: SonarCloud
        runs-on: ubuntu-24.04
        needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                fetch-depth: 0
            - name: Download coverage report
              uses: actions/download-artifact@v7
              with:
                name: coverage
            - name: Run SonarQube scan
              uses: minvws/action-sonarqube@v1
              with:
                sonar-token: ${{ secrets.SONAR_TOKEN }}

    image_scanner:
      name: Scan Docker image for vulnerabilities
      runs-on: ubuntu-24.04
      needs: [build, detect_modified_files]
      if: |
        github.ref == 'refs/heads/main' ||
        startsWith(github.ref, 'refs/tags/v') ||
        needs.detect_modified_files.outputs.image_files_changed == 'true'
      steps:
        - name: Checkout repository
          uses: actions/checkout@v6

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: docker/Dockerfile
            push: false
            tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.33.1
          with:
            image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
            format: "sarif"
            output: "trivy-results.sarif"
            exit-code: "0"
            severity: "CRITICAL,HIGH"
            vuln-type: "library"

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v4 # Don't clutter security tab on PRs
          if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') 
          with:
            sarif_file: "trivy-results.sarif"

        - name: Fail build on vulnerabilities
          uses: aquasecurity/trivy-action@0.33.1
          with:
            image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
            format: "table"
            exit-code: "1"
            severity: "CRITICAL,HIGH"
            vuln-type: "library"
            skip-setup-trivy: true

    detect_modified_files:
      name: Modified files
      runs-on: ubuntu-24.04
      outputs:
        dockerfile_changed: ${{ steps.dockerfile-changed.outputs.any_changed }}
        image_files_changed: ${{ steps.image-files-changed.outputs.any_changed }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v6
        - name: Check Dockerfile changes
          id: dockerfile-changed
          uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v46
          with:
            files: |
              docker/Dockerfile
        - name: Check image-related file changes
          id: image-files-changed
          uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v46
          with:
            files: |
              docker/Dockerfile
              pyproject.toml
              poetry.lock

    push_container:
        if: |
          github.ref == 'refs/heads/main' ||
          startsWith(github.ref, 'refs/tags/v') ||
          needs.detect_modified_files.outputs.dockerfile_changed == 'true'
        name: Create and publish Docker image to the Github Package Registry
        runs-on: ubuntu-24.04
        needs: [build, lint, type-check, safety-check, spelling-check, test, detect_modified_files]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              env:
                NEW_UID: 1000
                NEW_GID: 1000
              with:
                context: .
                file: docker/Dockerfile
                push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                build-args: |
                  NEW_UID=${{ env.NEW_UID }}
                  NEW_GID=${{ env.NEW_GID }}
                  standalone=true
